"""initial

Revision ID: b8cca355e504
Revises: 
Create Date: 2018-04-19 01:42:25.261413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8cca355e504'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partofspeech', sa.Column('part', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partofspeech', 'part')
    # ### end Alembic commands ###
