"""fix var

Revision ID: efae1c60e04e
Revises: b8cca355e504
Create Date: 2018-04-19 01:42:51.076875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efae1c60e04e'
down_revision = 'b8cca355e504'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partofspeech', 'part')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partofspeech', sa.Column('part', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
